export const IPC = {
  STUDENT_LIST: 'student:list',
  STUDENT_GET: 'student:get',
  STUDENT_CREATE: 'student:create',
  STUDENT_UPDATE: 'student:update',
  STUDENT_DELETE: 'student:delete',
  STUDENT_SET_COLOR: 'student:setColor',
  ROSTER_LIST: 'roster:list',
  ROSTER_MEMBERS: 'roster:members',
  ROSTER_SET_INCLUDED: 'roster:setIncluded',
  ROSTER_SET_ALL: 'roster:setAll',
  PICKER_LIST: 'picker:list',
  PICKER_PICK_RANDOM: 'picker:pickRandom',
  PICKER_PICK_STUDENT: 'picker:pickStudent',
  PICKER_SET_COUNT: 'picker:setCount',
  PICKER_RESET: 'picker:reset',
  PICKER_RECORD_MITARBEIT: 'picker:recordMitarbeit',

  CLASS_LIST: 'class:list',
  CLASS_CREATE: 'class:create',
  CLASS_UPDATE: 'class:update',
  CLASS_DELETE: 'class:delete',
  CLASS_DEPENDENTS: 'class:dependents',
  SCHOOLYEAR_PREVIEW: 'schoolyear:preview',
  SCHOOLYEAR_ROLLOVER: 'schoolyear:rollover',

  COURSE_LIST: 'course:list',
  COURSE_GET: 'course:get',
  COURSE_CREATE: 'course:create',
  COURSE_CLONE: 'course:clone',
  COURSE_UPDATE: 'course:update',
  COURSE_DELETE: 'course:delete',

  ASSESSMENT_CATEGORY_LIST_BY_COURSE: 'assessmentCategory:listByCourse',
  ASSESSMENT_CATEGORY_CREATE: 'assessmentCategory:create',
  ASSESSMENT_CATEGORY_UPDATE: 'assessmentCategory:update',
  ASSESSMENT_CATEGORY_DELETE: 'assessmentCategory:delete',

  SESSION_LIST_BY_COURSE: 'session:listByCourse',
  SESSION_CREATE: 'session:create',
  SESSION_UPDATE: 'session:update',
  SESSION_DELETE: 'session:delete',
  SESSION_SET_ABSENCE: 'session:setAbsence',

  ASSESSMENT_LIST_BY_SESSION: 'assessment:listBySession',
  ASSESSMENT_CREATE: 'assessment:create',
  ASSESSMENT_CREATE_IMPROMPTU: 'assessment:createImpromptu',
  ASSESSMENT_DELETE: 'assessment:delete',

  GRADE_DELETE_PERFORMANCE: 'grade:deletePerformance',
  GRADE_RECORD_PERFORMANCE: 'grade:recordPerformance',
  GRADE_GET_PERFORMANCES_BY_ASSESSMENT: 'grade:getPerformancesByAssessment',
  GRADE_LIST_BY_STUDENT: 'grade:listByStudent',
  GRADE_GET: 'grade:get',
  GRADE_CALCULATE_FINAL: 'grade:calculateFinal',
  GRADE_SAVE_MANUAL: 'grade:saveManualGrade',
  GRADE_RECORD_IMPROMPTU: 'grade:recordImpromptu',

  STUDENT_IMPORT_CSV: 'student:importCsv',
  IMPORT_DIGIGRADE: 'import:digigrade',

  FINDING_ADD: 'finding:add',
  FINDING_REMOVE: 'finding:remove',
  FINDING_GET: 'finding:getFindings',
  FINDING_LIST_NOTES_BY_SESSION: 'finding:listNotesBySession',
  FINDING_SET_NOTE: 'finding:setNote',

  GRADE_IMPORT_CSV: 'grade:importCsv',

  REPORT_GENERATE: 'report:generate',
  REPORT_GENERATE_SINGLE: 'report:generateSingle',

  SHOW_SETTINGS: 'show-settings',
  SETTINGS_GET_DB_PATH: 'settings:getDbPath',
  SETTINGS_PICK_DB_PATH: 'settings:pickDbPath',
  SETTINGS_SAVE_DB_PATH: 'settings:saveDbPath',
  SETTINGS_OPEN_DB: 'settings:openDb',
  SETTINGS_RESTART_APP: 'settings:restartApp',

  BIN_LIST: 'bin:list',
  BIN_RESTORE: 'bin:restore',
  BIN_HARD_DELETE: 'bin:hardDelete',
  BIN_EMPTY: 'bin:empty',

  MCP_GET_URL: 'mcp:getUrl',
  MCP_GET_SETTINGS: 'mcp:getSettings',
  MCP_SET_ENABLED: 'mcp:setEnabled',
  MCP_STATUS_CHANGE: 'mcp:statusChange',
} as const;
