@startuml
'https://plantuml.com/class-diagram

hide empty attributes
hide empty methods

enum ParticipationSymbol {
    PLUS <<P>>
    MINUS <<M>>
    WELLE <<W>>
}

enum GradingType {
    TERTIARY <<T>>
    NUMERIC <<N>>
}

entity Name <ValueObject> <<(V, bbFFcc)>> {
    - lastName: String {nn}
    - firstName: String {nn}
}

entity SchoolClass <Entity> {
    - name: String {nn}
    - schoolYear: String {nn}
    - courses: List<Course>
}

entity Student <Entity> {
    - name: Name
    - schoolClass: SchoolClass
    - additionalInformation: List<AdditionalInformation>
    - performances: List<StudentPerformance>
}

entity AdditionalInformation <ValueObject> <<(V, bbFFcc)>> {
    - key: String {unique, nn}
    - value: String
}

entity StudentPerformance <Entity> {
    - date: DateTime {nn}
    - student: Student {nn}
    - assessment: Assessment {nn}
    - findings: List<Finding>
    - score: Integer {gt: -1}
}

entity Finding <AbstractEntity> {

}

entity Document <Entity> {
    - filePath: String
}

entity Note <Entity> {
    - text: String
}

entity RemoteDocument <Entity> {
    - url: URL {nn}
}

entity AssessmentCategory <Entity> {
    - title: String {nn}
    - gradingType: GradingType {nn}
    - displayAsGrade: boolean
}

entity Assessment <Entity> {
    - date: DateTime
    - title: String {nn}
    - category: AssessmentCategory {nn}
    - course: Course {nn}
    - performances: List<StudentPerformance>
    - isImpromptu: boolean
}

entity GradedAssessment <Entity> {
    - maxPoints: Integer {gt: 0}
}

entity Course <Entity> {
    - title: String {nn, unique}
    - schoolClass: SchoolClass {nn}
    - gradeCompositions: List<GradeComposition>
    - assessmentCategories: List<AssessmentCategory>
    - assessments: List<Assessment>
    - sessions: List<Session>
    - grades: List<Grade>
}

entity Session <Entity> {
    - date: DateTime {nn}
    - notes: String
    - students: List<Student>
}

entity GradeComposition <ValueObject> <<(V, bbFFcc)>> {
    - category: AssessmentCategory
    - weight: Float {gt: 0, lt: 100}
}

entity Grade <Entity> {
    - student: Student {nn}
    - score: Integer {nn, gt: 0, lt: 6}
}

' Relationships

Student --> Name
Student "1" --* "0..*" AdditionalInformation

Student "0..*" *-- "1" SchoolClass
Student "1" --* "0..*" StudentPerformance
StudentPerformance "0..*" *-- "1" Assessment
Assessment "0..*" *-- "1" Course
Assessment --> GradingType
Course "0..*" *-- "1" SchoolClass
Course "1" --* "1..*" GradeComposition

Student "0..*" o-- "0..*" Session
Assessment "0..*" o-- "1" Session
Course "1" --* "0..*" Session

StudentPerformance "1" --* "0..*" Finding

ParticipationPerformance --> ParticipationSymbol

Assessment --> AssessmentCategory
Course "1" --* "0..*" AssessmentCategory

Student <-- Grade
Course "1" --* "0..*" Grade

' Inheritance

StudentPerformance <|-- ParticipationPerformance
StudentPerformance <|-- GradedPerformance

Finding <|-- Document
Finding <|-- Note
Finding <|-- RemoteDocument

Assessment <|-- GradedAssessment

@enduml
